from model import Pokemon

datos_pokemon = [
    {"id": 1, "name": "Bulbasaur", "attack": 49.0, "life": 45.0, "type": "Grass"},
    {"id": 2, "name": "Ivysaur", "attack": 62.0, "life": 60.0, "type": "Grass"},
    {"id": 3, "name": "Venusaur", "attack": 82.0, "life": 80.0, "type": "Grass"},
    {"id": 4, "name": "Charmander", "attack": 52.0, "life": 39.0, "type": "Fire"},
    {"id": 5, "name": "Charmeleon", "attack": 64.0, "life": 58.0, "type": "Fire"},
    {"id": 6, "name": "Charizard", "attack": 84.0, "life": 78.0, "type": "Fire"},
    {"id": 7, "name": "Squirtle", "attack": 48.0, "life": 44.0, "type": "Water"},
    {"id": 8, "name": "Wartortle", "attack": 63.0, "life": 59.0, "type": "Water"},
    {"id": 9, "name": "Blastoise", "attack": 83.0, "life": 79.0, "type": "Water"},
    {"id": 10, "name": "Caterpie", "attack": 30.0, "life": 45.0, "type": "Bug"},
    {"id": 11, "name": "Metapod", "attack": 20.0, "life": 50.0, "type": "Bug"},
    {"id": 12, "name": "Butterfree", "attack": 45.0, "life": 60.0, "type": "Bug"},
    {"id": 13, "name": "Weedle", "attack": 35.0, "life": 40.0, "type": "Bug"},
    {"id": 14, "name": "Kakuna", "attack": 25.0, "life": 45.0, "type": "Bug"},
    {"id": 15, "name": "Beedrill", "attack": 90.0, "life": 65.0, "type": "Bug"},
    {"id": 16, "name": "Pidgey", "attack": 45.0, "life": 40.0, "type": "Normal"},
    {"id": 17, "name": "Pidgeotto", "attack": 60.0, "life": 63.0, "type": "Normal"},
    {"id": 18, "name": "Pidgeot", "attack": 80.0, "life": 83.0, "type": "Normal"},
    {"id": 19, "name": "Rattata", "attack": 56.0, "life": 30.0, "type": "Normal"},
    {"id": 20, "name": "Raticate", "attack": 81.0, "life": 55.0, "type": "Normal"},
    {"id": 21, "name": "Spearow", "attack": 60.0, "life": 40.0, "type": "Normal"},
    {"id": 22, "name": "Fearow", "attack": 90.0, "life": 65.0, "type": "Normal"},
    {"id": 23, "name": "Ekans", "attack": 60.0, "life": 35.0, "type": "Poison"},
    {"id": 24, "name": "Arbok", "attack": 85.0, "life": 60.0, "type": "Poison"},
    {"id": 25, "name": "Pikachu", "attack": 55.0, "life": 35.0, "type": "Electric"},
    {"id": 26, "name": "Raichu", "attack": 90.0, "life": 60.0, "type": "Electric"},
    {"id": 27, "name": "Sandshrew", "attack": 75.0, "life": 50.0, "type": "Ground"},
    {"id": 28, "name": "Sandslash", "attack": 100.0, "life": 75.0, "type": "Ground"},
    {"id": 29, "name": "Nidoran F", "attack": 47.0, "life": 55.0, "type": "Poison"},
    {"id": 30, "name": "Nidorina", "attack": 62.0, "life": 70.0, "type": "Poison"},
    {"id": 31, "name": "Nidoqueen", "attack": 92.0, "life": 90.0, "type": "Poison"},
    {"id": 32, "name": "Nidoran M", "attack": 57.0, "life": 46.0, "type": "Poison"},
    {"id": 33, "name": "Nidorino", "attack": 72.0, "life": 61.0, "type": "Poison"},
    {"id": 34, "name": "Nidoking", "attack": 102.0, "life": 81.0, "type": "Poison"},
    {"id": 35, "name": "Clefairy", "attack": 45.0, "life": 70.0, "type": "Fairy"},
    {"id": 36, "name": "Clefable", "attack": 70.0, "life": 95.0, "type": "Fairy"},
    {"id": 37, "name": "Vulpix", "attack": 41.0, "life": 38.0, "type": "Fire"},
    {"id": 38, "name": "Ninetales", "attack": 76.0, "life": 73.0, "type": "Fire"},
    {"id": 39, "name": "Jigglypuff", "attack": 45.0, "life": 115.0, "type": "Normal"},
    {"id": 40, "name": "Wigglytuff", "attack": 70.0, "life": 140.0, "type": "Normal"},
    {"id": 41, "name": "Zubat", "attack": 45.0, "life": 40.0, "type": "Poison"},
    {"id": 42, "name": "Golbat", "attack": 80.0, "life": 75.0, "type": "Poison"},
    {"id": 43, "name": "Oddish", "attack": 50.0, "life": 45.0, "type": "Grass"},
    {"id": 44, "name": "Gloom", "attack": 65.0, "life": 60.0, "type": "Grass"},
    {"id": 45, "name": "Vileplume", "attack": 80.0, "life": 75.0, "type": "Grass"},
    {"id": 46, "name": "Paras", "attack": 70.0, "life": 35.0, "type": "Bug"},
    {"id": 47, "name": "Parasect", "attack": 95.0, "life": 60.0, "type": "Bug"},
    {"id": 48, "name": "Venonat", "attack": 55.0, "life": 60.0, "type": "Bug"},
    {"id": 49, "name": "Venomoth", "attack": 65.0, "life": 70.0, "type": "Bug"},
    {"id": 50, "name": "Diglett", "attack": 55.0, "life": 10.0, "type": "Ground"}
]

# Multiplicamos la vida por 5 para que duren más los combates
lista_pokemon: list[Pokemon] = [
    Pokemon(**{**p, "life": p["life"] * 5}) 
    for p in datos_pokemon
]